pipeline {
	agent {
		label 'master'
		}
	stages {
		stage("Create artifact") {
			steps ('Build') {
				echo "========= start building artifact ========="
				dir ('./') {
					sh 'python3 setup.py sdist bdist_wheel'
					}
				}
			}
	
		stage('Push artifac') {
			steps ('PUSHING to Nexus'){
				withCredentials([string(credentialsId: 'Nexus_1', variable: 'Nexus_1')]) {
					sh "curl -v -u admin -p ${Nexus_1} --upload-file dist/helloworls-0.0.1.tar.gz http://54.191.157.240:8081/repository/Py_HelloWorld/"
				}
			}
		}
  }
}
